owner: dorwardtech
repo: status 

sites:
  - name: ZLTAC Main Site (Managed by Tr1cky)
    url: https://zltac.com.au
  - name: TORN 5 (Managed By Doug & AJ)
    url: https://torn.lasersports.au
  - name: LSA - Northern Territory (Managed by Tr1cky)
    url: https://nt.lasersports.au
      
status-website:
  cname: status.tr1cky.au
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Tr1ckCheck
  theme: dark
  introTitle: "**Tr1ckCheck** Hosted by Tr1cky"
  introMessage: Projects that are hosted by Tr1cky, all credits to the developers & owners. I just have fancy server.

