# Change these first
owner: dorwardtech # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: ZLTAC Main Site
    url: https://zltac.com.au
    assignees:
      - DorwardTech
  - name: TORN (Doug & AJ)
    url: https://torn.lasersports.au
    assignees:
      - DorwardTech
      - MrMeeseeks200
  - name: LSA - Northern Territory
    url: https://nt.lasersports.au
    assignees:
      - DorwardTech
      
status-website:
  cname: status.tr1cky.au
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Tr1cky Uptime Status
  introTitle: "Are any of Tr1cky's projects online or is he bin"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
