owner: dorwardtech
repo: status 

sites:
  - name: ZLTAC Main Site
    url: https://zltac.com.au
  - name: TORN 5
    url: https://torn.lasersports.au
  - name: Laser Sports Archive
    url: https://archive.lasersports.au
  - name: Top End Laser Sports Association
    url: https://nt.lasersports.au
  - name: Tr1cky Home Page
    url: https://tr1cky.au
      
status-website:
  cname: status.tr1cky.au
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Tr1ckCheck
  theme: dark
  introTitle: "**Tr1ckCheck**"
  introMessage: Projects that are hosted by Tr1cky, all credits to the developers & owners. I just have fancy server.

